substitutions:
  name: "power-relays"
  friendly_name: Power Relays

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: esp01_1m
  early_pin_init: false

# Enable logging
logger:
  baud_rate: 0
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption: 
    key: !secret haapi_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

# Allow provisioning Wi-Fi via serial
#improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#  manual_ip:
#    static_ip: 10.0.0.32
#    gateway: 10.0.0.1
#    subnet: 255.255.255.0
#    dns1: 75.75.75.75
#    dns2: 75.75.76.76
  
  fast_connect: off

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "power-relays"
    password: "2012VolksBeet"

#captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

time:
  - platform: homeassistant
    id: esptime

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Power Relays IP
    ssid:
      name: Power Relays SSID
    mac_address:
      name: Power Relays Mac
i2c:
  sda: GPIO10 #SD3 Yellow
  scl: GPIO9 #SD2 Green

sensor:
  - platform: wifi_signal
    name: "Power Relays Signal Strength"
    update_interval: 60s

switch:
  - platform: restart
    name: "Power Relays Restart"

  - platform: gpio
    pin: GPIO5 #D1
    name: "Relay 1" #Relay 1 Green
    id: relay1_relay
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: GPIO4 #D2
    name: "Relay 2" #Relay 2 Yellow
    id: relay2_relay
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: GPIO14 #D5
    name: "Relay 3" #Relay 3 Blue
    id: relay3_relay
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: GPIO12 #D6
    name: "Relay 4" #Relay 4 White
    id: relay4_relay
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF

# Individual button sensors
binary_sensor:
# Reports when the button is pressed
- platform: gpio
  pin:
    number: GPIO1 #TX
    mode: INPUT_PULLUP
    inverted: True
  name: Relay 1 Button
  on_press:
    - switch.toggle: relay1_relay

- platform: gpio
  pin:
    number: GPIO3 #RX
    mode: INPUT_PULLUP
    inverted: True
  name: Relay 2 Button
  on_press:
    - switch.toggle: relay2_relay

- platform: gpio
  pin:
    number: GPIO2 #D4
    mode: INPUT_PULLUP
    inverted: True
  name: Relay 3 Button
  on_press:
    - switch.toggle: relay3_relay

- platform: gpio
  pin:
    number: GPIO13 #D7
    mode: INPUT_PULLUP
    inverted: True
  name: Relay 4 Button
  on_press:
    - switch.toggle: relay4_relay

